### ISSUE TITLE
esp32c6 

### ISSUE THREAD

**Issue by maedoc** [toitlang/envelopes#69]
hi, Toit looks interesting, but I don't see a c6 envelope in the release section.  is there an easy way to build one?

**Comment by floitsch** [comment]
I'm looking into this.
As you mentioned, the fork we are using doesn't support the C6 yet.
I'm trying to upgrade to a newer version, but am running into issues (memory corruption and crashes). I'm now debugging them, but it's impossible to say how long that will take.

**Comment by floitsch** [comment]
An esp32c6 envelope was added with https://github.com/toitlang/envelopes/commit/dba3567222f4eabb13a1df5e878f3c60d7086ab0

The envelope is still new and probably isn't as stable as the esp32 envelopes yet, but in my testing it worked without issues.
